# Generated by Django 3.1.7 on 2022-02-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lootmanage', '0002_auto_20220206_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='hope',
            field=models.BooleanField(default=True, verbose_name='希望品'),
        ),
    ]
