# Generated by Django 3.1.7 on 2022-02-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lootmanage', '0003_drop_hope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drop',
            name='hope',
        ),
    ]
